import { createHash, generateKeyPairSync, sign } from "node:crypto";
import { mkdir, mkdtemp, rename, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { capturePackagePayloadSha256 } from "../src/publicationTrust.js";
import { readLivePublicationTrust, verifyAndStorePublicationTrust } from "../src/publicationTrustStore.js";

const intent = { intentId: "trust-proof", operation: "verify-publication-capture" as const, objective: "Verify exact capture publication evidence", writeScope: ["project-state", "manifest"] as const, forbiddenScope: ["source-measurements", "locked-geometry"] as const, selectedToolPath: "mcp:nova-measured" as const, acceptanceChecks: ["schema", "quality-gate", "manifest"] as const, executionPolicy: { locality: "local-only" as const, telemetry: false, fallback: "none" as const, geometryMutation: false } };

describe("publication trust store", () => {
  it("persists verified native evidence and disputes later byte mutation", async () => {
    const outputDir = await mkdtemp(path.join(os.tmpdir(), "publication-trust-"));
    const projectId = "trust-project";
    const packageDir = path.join(outputDir, "captures", "native-1");
    await mkdir(path.join(outputDir, "measurement-projects", projectId), { recursive: true });
    await mkdir(packageDir, { recursive: true });
    await mkdir(path.join(outputDir, "publication-keys"));
    await writeFile(path.join(outputDir, "measurement-projects", projectId, "project.json"), JSON.stringify({ projectId }));
    const artifact = Buffer.from("signed capture evidence");
    await writeFile(path.join(packageDir, "evidence.json"), artifact);
    const binding = { schemaVersion: 1 as const, packageId: "native-1", projectId, objectId: "object-1", captureProtocolId: "protocol-1", kitId: "kit-1", commissioningPartyId: "party-1", capturedAt: "2026-08-16T00:00:00.000Z", evidenceScopes: [{ id: "dimensions", kind: "measurement" as const, required: true, verified: true }], manifest: [{ path: "evidence.json", sha256: createHash("sha256").update(artifact).digest("hex"), sizeBytes: artifact.byteLength }] };
    const { privateKey, publicKey } = generateKeyPairSync("ed25519");
    const payloadHash = capturePackagePayloadSha256(binding);
    await writeFile(path.join(outputDir, "publication-keys", "native-key-1.pem"), publicKey.export({ type: "spki", format: "pem" }));
    const packageDocument = { source: "native_app", binding, signature: { algorithm: "Ed25519", keyId: "native-key-1", publicKeyFingerprintSha256: createHash("sha256").update(publicKey.export({ type: "spki", format: "der" })).digest("hex"), signedPayloadSha256: payloadHash, valueBase64: sign(null, Buffer.from(payloadHash, "hex"), privateKey).toString("base64") }, nativeEvidence: { adapter: "measured-native-macos", adapterVersion: 1, platform: "macos", consent: { method: "device_owner_authentication", eventId: "6e5a0fe7-23a7-4ac5-87ea-61b4654df129", occurredAt: "2026-08-31T20:00:00.000Z" } };
    const packageBytes = JSON.stringify(packageDocument);
    await writeFile(path.join(packageDir, "capture-package.json"), packageBytes);
    const input = { projectId, executionIntent: intent, packageManifestPath: "captures/native-1/capture-package.json", publicKeyPath: "publication-keys/native-key-1.pem", disputes: [] };
    expect((await verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, input)).classification.category).toBe("verified");
    await writeFile(path.join(packageDir, "capture-package.json"), JSON.stringify(packageDocument, null, 2));
    expect((await readLivePublicationTrust({ outputDir, timeoutMs: 1 }, projectId))?.classification).toMatchObject({ category: "disputed", verifiedScopeIds: [], unverifiedRequiredScopeIds: ["dimensions"] });
    await writeFile(path.join(packageDir, "capture-package.json"), packageBytes);
    await Promise.all([
      verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, { ...input, disputes: [{ scopeId: "dimensions", status: "open", reason: "Operator dispute remains open." }] }),
      verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, input)
    ]);
    expect((await readLivePublicationTrust({ outputDir, timeoutMs: 1 }, projectId))?.classification).toMatchObject({ category: "disputed", verifiedScopeIds: ["dimensions"], disputedScopeIds: ["dimensions"] });
    await writeFile(path.join(packageDir, "evidence.json"), "mutated");
    expect((await readLivePublicationTrust({ outputDir, timeoutMs: 1 }, projectId))?.classification.category).toBe("disputed");
    await rm(path.join(packageDir, "evidence.json"));
    expect((await readLivePublicationTrust({ outputDir, timeoutMs: 1 }, projectId))?.verification.codes).toContain("artifact_missing");
    await writeFile(path.join(packageDir, "evidence.json"), artifact);
    await writeFile(path.join(packageDir, "undeclared.txt"), "unexpected");
    expect((await readLivePublicationTrust({ outputDir, timeoutMs: 1 }, projectId))?.verification.codes).toContain("artifact_unexpected");
    await rm(path.join(packageDir, "undeclared.txt"));
    await writeFile(path.join(outputDir, "publication-keys", "revoked-key-ids.json"), JSON.stringify({ schemaVersion: 1, revokedKeyIds: ["native-key-1"] }));
    const revoked = await verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, input);
    expect(revoked.classification.category).toBe("disputed");
    expect(revoked.verification.codes).toContain("signing_key_revoked");
    const externalRegistry = path.join(await mkdtemp(path.join(os.tmpdir(), "publication-registry-")), "revoked-key-ids.json");
    await writeFile(externalRegistry, JSON.stringify({ schemaVersion: 1, revokedKeyIds: [] }));
    await rm(path.join(outputDir, "publication-keys", "revoked-key-ids.json"));
    await symlink(externalRegistry, path.join(outputDir, "publication-keys", "revoked-key-ids.json"));
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, input)).rejects.toThrow("publication_trust_path_escape");
    await rm(path.join(outputDir, "publication-keys", "revoked-key-ids.json"));
    await writeFile(path.join(outputDir, "publication-keys", "revoked-key-ids.json"), JSON.stringify({ schemaVersion: 1, revokedKeyIds: [] }));
    await writeFile(path.join(outputDir, "publication-keys", "native-key-1.pem"), privateKey.export({ type: "pkcs8", format: "pem" }));
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, input)).rejects.toThrow("publication_trust_private_key_forbidden");
    const { publicKey: rsaPublicKey } = generateKeyPairSync("rsa", { modulusLength: 2048 });
    await writeFile(path.join(outputDir, "publication-keys", "native-key-1.pem"), rsaPublicKey.export({ type: "spki", format: "pem" }));
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, input)).rejects.toThrow("publication_trust_key_algorithm_invalid");
    await writeFile(path.join(outputDir, "publication-keys", "native-key-1.pem"), publicKey.export({ type: "spki", format: "pem" }));
    await writeFile(path.join(outputDir, "publication-keys", "revoked-key-ids.json"), "{");
    expect((await readLivePublicationTrust({ outputDir, timeoutMs: 1 }, projectId))?.verification.codes).toEqual(["publication_trust_revocation_registry_invalid"]);
    const externalKeys = await mkdtemp(path.join(os.tmpdir(), "publication-external-keys-"));
    await writeFile(path.join(externalKeys, "native-key-1.pem"), publicKey.export({ type: "spki", format: "pem" }));
    await rm(path.join(outputDir, "publication-keys"), { recursive: true });
    await symlink(externalKeys, path.join(outputDir, "publication-keys"));
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, input)).rejects.toThrow("publication_trust_key_root_escape");
  });

  it("keeps manual packages reference even with verified scopes", async () => {
    const outputDir = await mkdtemp(path.join(os.tmpdir(), "publication-reference-"));
    const projectId = "reference-project";
    const packageDir = path.join(outputDir, "captures", "manual-1");
    await mkdir(path.join(outputDir, "measurement-projects", projectId), { recursive: true });
    await mkdir(packageDir, { recursive: true });
    await writeFile(path.join(outputDir, "measurement-projects", projectId, "project.json"), JSON.stringify({ projectId }));
    await writeFile(path.join(packageDir, "evidence.json"), "manual");
    const content = Buffer.from("manual");
    const binding = { schemaVersion: 1, packageId: "manual-1", projectId, objectId: "object-1", captureProtocolId: "protocol-1", kitId: "kit-1", commissioningPartyId: "party-1", capturedAt: "2026-08-16T00:00:00.000Z", evidenceScopes: [{ id: "dimensions", kind: "measurement", required: true, verified: true }], manifest: [{ path: "evidence.json", sha256: createHash("sha256").update(content).digest("hex"), sizeBytes: content.byteLength }] };
    await writeFile(path.join(packageDir, "capture-package.json"), JSON.stringify({ source: "manual_upload", binding }));
    const result = await verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, { projectId, executionIntent: intent, packageManifestPath: "captures/manual-1/capture-package.json" });
    expect(result.classification.category).toBe("reference");
    expect(result.verification.codes).toContain("manual_upload");
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, { projectId, executionIntent: intent, packageManifestPath: "captures/manual-1/capture-package.json", publicKeyPath: "publication-keys/nonexistent.pem" })).rejects.toThrow("publication_trust_manual_key_forbidden");
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, { projectId, executionIntent: intent, packageManifestPath: "captures/manual-1/capture-package.json", disputes: [{ scopeId: "unknown", status: "open", reason: "Not a signed scope." }] })).rejects.toThrow("publication_trust_dispute_scope_unknown");
    await writeFile(path.join(packageDir, "evidence.json"), "changed manual evidence");
    expect((await readLivePublicationTrust({ outputDir, timeoutMs: 1 }, projectId))?.classification.category).toBe("disputed");
    await writeFile(path.join(packageDir, "capture-package.json"), JSON.stringify({ source: "manual_upload", binding: { ...binding, manifest: [{ ...binding.manifest[0], sizeBytes: 2 * 1024 * 1024 * 1024 + 1 }] } }));
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, { projectId, executionIntent: intent, packageManifestPath: "captures/manual-1/capture-package.json" })).rejects.toThrow("publication_trust_package_bytes_exceeded");
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, { projectId, executionIntent: intent, packageManifestPath: `measurement-projects/${projectId}/capture-package.json` })).rejects.toThrow("publication_trust_package_root_reserved");
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, { projectId, executionIntent: intent, packageManifestPath: `./measurement-projects/${projectId}/capture-package.json` })).rejects.toThrow("publication_trust_package_root_reserved");
    const trustPath = path.join(outputDir, "measurement-projects", projectId, ".publication-trust.json");
    await writeFile(trustPath, JSON.stringify({ ...result, projectId: "different-project" }));
    expect((await readLivePublicationTrust({ outputDir, timeoutMs: 1 }, projectId))?.classification.category).toBe("disputed");
    await writeFile(trustPath, "{");
    expect(await readLivePublicationTrust({ outputDir, timeoutMs: 1 }, projectId)).toMatchObject({ verification: { valid: false, codes: ["publication_trust_evidence_invalid"] }, classification: { category: "disputed", verifiedScopeIds: [] } });
    await rm(trustPath);
    const externalRoot = await mkdtemp(path.join(os.tmpdir(), "publication-project-root-"));
    const projectsRoot = path.join(outputDir, "measurement-projects");
    const movedProjectsRoot = path.join(externalRoot, "measurement-projects");
    await rename(projectsRoot, movedProjectsRoot);
    await symlink(movedProjectsRoot, projectsRoot);
    await expect(verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, { projectId, executionIntent: intent, packageManifestPath: "captures/manual-1/capture-package.json" })).rejects.toThrow("publication_trust_project_path_escape");
  });

  it("never publishes verified trust while an artifact pathname is replaced", async () => {
    const outputDir = await mkdtemp(path.join(os.tmpdir(), "publication-race-"));
    const projectId = "race-project";
    const packageDir = path.join(outputDir, "captures", "native-race");
    await mkdir(path.join(outputDir, "measurement-projects", projectId), { recursive: true });
    await mkdir(path.join(outputDir, "publication-keys"));
    await mkdir(packageDir, { recursive: true });
    await writeFile(path.join(outputDir, "measurement-projects", projectId, "project.json"), JSON.stringify({ projectId }));
    const artifact = Buffer.alloc(64 * 1024 * 1024, 0x61);
    const replacement = Buffer.alloc(64 * 1024 * 1024, 0x62);
    const artifactPath = path.join(packageDir, "evidence.bin");
    const replacementPath = path.join(outputDir, "replacement.bin.pending");
    const retiredPath = path.join(outputDir, "retired-evidence.bin");
    await writeFile(artifactPath, artifact);
    await writeFile(replacementPath, replacement);
    const binding = { schemaVersion: 1 as const, packageId: "native-race", projectId, objectId: "object-1", captureProtocolId: "protocol-1", kitId: "kit-1", commissioningPartyId: "party-1", capturedAt: "2026-08-16T00:00:00.000Z", evidenceScopes: [{ id: "dimensions", kind: "measurement" as const, required: true, verified: true }], manifest: [{ path: "evidence.bin", sha256: createHash("sha256").update(artifact).digest("hex"), sizeBytes: artifact.byteLength }] };
    const { privateKey, publicKey } = generateKeyPairSync("ed25519");
    const payloadHash = capturePackagePayloadSha256(binding);
    await writeFile(path.join(outputDir, "publication-keys", "race-key.pem"), publicKey.export({ type: "spki", format: "pem" }));
    await writeFile(path.join(packageDir, "capture-package.json"), JSON.stringify({ source: "native_app", binding, signature: { algorithm: "Ed25519", keyId: "race-key", publicKeyFingerprintSha256: createHash("sha256").update(publicKey.export({ type: "spki", format: "der" })).digest("hex"), signedPayloadSha256: payloadHash, valueBase64: sign(null, Buffer.from(payloadHash, "hex"), privateKey).toString("base64") }, nativeEvidence: { adapter: "measured-native-macos", adapterVersion: 1, platform: "macos", consent: { method: "device_owner_authentication", eventId: "6e5a0fe7-23a7-4ac5-87ea-61b4654df129", occurredAt: "2026-08-31T20:00:00.000Z" } }));
    const verification = verifyAndStorePublicationTrust({ outputDir, timeoutMs: 1 }, { projectId, executionIntent: intent, packageManifestPath: "captures/native-race/capture-package.json", publicKeyPath: "publication-keys/race-key.pem" });
    await new Promise((resolve) => setTimeout(resolve, 5));
    await rename(artifactPath, retiredPath);
    await rename(replacementPath, artifactPath);
    const outcome = await verification.then((result) => ({ result })).catch((error: unknown) => ({ error }));
    if ("result" in outcome) expect(outcome.result.classification.category).toBe("disputed");
    else expect(outcome.error).toMatchObject({ message: "publication_trust_package_changed_during_verification" });
  });
});
